const sampleCourses = [
    {
      id: 1,
      name: 'CSS Course',
      instructor: 'Girija Shankar',
      description: 'Description for Course 1',
      status: 'Open',
      duration: '8 weeks',
      schedule: 'Mon, Wed, Fri',
      location: 'Online',
      prerequisites: 'None',
      syllabus: 'Course syllabus goes here...',
      image: 'https://www.w3docs.com/uploads/media/default/0001/05/6d07a36ebe6d55273b39440f2391f1d7e6d4092a.png',
    },
    {
        id: 2,
        name: 'HTML  Course',
        instructor: 'Shankar Mohanta',
        description: 'Description for Course 1',
        status: 'Open',
        duration: '7 weeks',
        schedule: 'Mon, Wed, Fri',
        location: 'Online',
        prerequisites: 'None',
        syllabus: 'Course syllabus goes here...',
        image: 'https://d1jnx9ba8s6j9r.cloudfront.net/imgver.1551437392/img/co_img_1518_1631724053.png',
      },
      {
        id: 3,
        name: 'Python Course',
        instructor: 'Dr. Manas Ranjan',
        description: 'Learn Python from scratch and become a Python expert.',
        status: 'Open',
        duration: '8 weeks',
        schedule: 'Tue, Thu',
        location: 'Online',
        prerequisites: 'Basic programming knowledge is recommended.',
        syllabus: 'Course syllabus goes here...',
        image: 'https://trisectinstitute.com/wp-content/uploads/2021/12/best-python-training.png',
      },
      {
        id: 4,
        name: 'Machine Learning ',
        instructor: 'Sambit Smith',
        description: 'Explore the fundamentals of machine learning and data analysis.',
        status: 'Open',
        duration: '10 weeks',
        schedule: 'Mon, Wed',
        location: 'Online',
        prerequisites: 'Basic understanding of programming and mathematics.',
        syllabus: 'Course syllabus goes here...',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToCKJ7kOFFIxJYr__UXFFg9qbRgfH_1W7qYg&usqp=CAU',
      },
      {
        id: 5,
        name: 'Web Development',
        instructor: 'Girija Mohanta',
        description: 'Become a web development pro in just 6 weeks.',
        status: 'Open',
        duration: '6 weeks',
        schedule: 'Tue, Thu, Sat',
        location: 'Online',
        prerequisites: 'No prior experience required.',
        syllabus: 'Course syllabus goes here...',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp71bMNhc491wpEmqoDRNybniIVMKOOfRnAI8J9Va9lTTRYM1BBG2aEK1422jPNi7CykI&usqp=CAU',
      },
      {
        id: 6,
        name: 'Data Science',
        instructor: 'Dr. G S M',
        description: 'An introductory course to the world of data science.',
        status: 'Open',
        duration: '12 weeks',
        schedule: 'Mon, Wed, Fri',
        location: 'Online',
        prerequisites: 'Basic knowledge of statistics is recommended.',
        syllabus: 'Course syllabus goes here...',
        image: 'https://s40424.pcdn.co/in/wp-content/uploads/2023/08/Featured-Images-April-28-1140x628.png.webp',
      },
      {
        id: 7,
        name: 'Java',
        instructor: 'Jagatjit Barik',
        description: 'Master the art of Java programming from scratch.',
        status: 'Open',
        duration: '9 weeks',
        schedule: 'Mon, Wed',
        location: 'Online',
        prerequisites: 'No prior programming experience required.',
        syllabus: 'Course syllabus goes here...',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdbO89i5oTybW6jIf-6Vyy9LU1V8gAzRZK79hUCTtKhbt7PiZb79_50qM6mJfjPhwR_Yw&usqp=CAU',
      },
      {
        id: 8,
        name: 'Cybersecurity',
        instructor: 'Babun Kumar',
        description: 'Learn the basics of cybersecurity and protect your digital world.',
        status: 'Open',
        duration: '7 weeks',
        schedule: 'Tue, Thu',
        location: 'Online',
        prerequisites: 'Basic computer skills are recommended.',
        syllabus: 'Course syllabus goes here...',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDOI6LurWiGBb3w9KdmruY2PGG6RQtrQepLfmMvZalCfRKKI0oyDtn-gCAdECtKXbqRyM&usqp=CAU',
      },
      {
        id: 9,
        name: 'Mobile App ',
        instructor: 'SatyaBratya Giri',
        description: 'Build cross-platform mobile apps using React Native.',
        status: 'Open',
        duration: '8 weeks',
        schedule: 'Tue, Thu',
        location: 'Online',
        prerequisites: 'Familiarity with JavaScript is a plus.',
        syllabus: 'Course syllabus goes here...',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGA7iuRQkXsoTu33evQNeCFsw5CugghbukognkWFJcBixtnDN0TwHfjGiKpxhU5LzOnSM&usqp=CAU',
      }
      
      
      
      
      

  
  ];
  
  export default sampleCourses;
  